/* ============================================================================
   icons.js — NAME → ICON REGISTRY
   ----------------------------------------------------------------------------
   config/navigation.js and config/constants.js refer to icons by name so they
   stay free of JSX and of any dependency on the icon library. This module is
   the only place that resolves a name to an Untitled UI icon component, so
   swapping icon sets is a change to this file alone.
   ========================================================================== */

import {
    Activity,
    AlertTriangle,
    Announcement02,
    Archive,
    ArrowLeft,
    ArrowRight,
    Bell01,
    Building07,
    Calendar,
    Check,
    CheckCircle,
    CheckDone01,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Clipboard,
    ClipboardCheck,
    Clock,
    Copy01,
    Download01,
    Droplets01,
    Edit03,
    Eye,
    File02,
    FileCheck02,
    FilterFunnel01,
    Folder,
    Grid01,
    InfoCircle,
    Inbox01,
    LogOut01,
    Lock01,
    Mail01,
    Menu02,
    Monitor01,
    Paperclip,
    PieChart03,
    Plus,
    PlusCircle,
    Printer,
    RefreshCcw01,
    ReverseLeft,
    SearchLg,
    Send01,
    Settings01,
    Shield01,
    ShieldTick,
    Trash01,
    TrendUp02,
    Upload01,
    User01,
    UserCircle,
    Users01,
    UserSquare,
    X,
    XCircle,
} from '@untitledui/icons'

/** Every icon the app refers to by name. */
export const ICONS = {
  dashboard: Grid01,
  folder: Folder,
  file: File02,
  'file-check': FileCheck02,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'plus-circle': PlusCircle,
  plus: Plus,
  bell: Bell01,
  history: Activity,
  chart: PieChart03,
  trend: TrendUp02,
  users: Users01,
  user: User01,
  personnel: UserSquare,
  account: UserCircle,
  monitor: Monitor01,
  settings: Settings01,
  search: SearchLg,
  download: Download01,
  upload: Upload01,
  eye: Eye,
  check: Check,
  'check-circle': CheckCircle,
  'check-done': CheckDone01,
  x: X,
  'x-circle': XCircle,
  alert: AlertTriangle,
  clock: Clock,
  undo: ReverseLeft,
  shield: Shield01,
  'shield-tick': ShieldTick,
  car: ClipboardCheck,
  filter: FilterFunnel01,
  chevron: ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  menu: Menu02,
  logout: LogOut01,
  print: Printer,
  paperclip: Paperclip,
  archive: Archive,
  trash: Trash01,
  edit: Edit03,
  refresh: RefreshCcw01,
  building: Building07,
  droplet: Droplets01,
  inbox: Inbox01,
  lock: Lock01,
  info: InfoCircle,
  calendar: Calendar,
  mail: Mail01,
  send: Send01,
  copy: Copy01,
  announcement: Announcement02,
}

/** Resolve a name to an icon component. Unknown names fall back to a dot-free box. */
export function icon(name) {
  return ICONS[name] || InfoCircle
}
